[package]
name = "signify-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
libsignify = { version = "0.6", features = ["std"] }
serde = { version = "1", features = ["derive"] }
base64ct = { version = "1", features = ["std"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
hex = "0.4.3"
snafu = "0.8"

rand_core = { version = "0.6.4", optional = true, features = ["std"] }
jiff = "0.1"

serde_json = "1"
ciborium = "0.2.2"
serde_yaml = "0.9"
toml = "0.8"
bson = "2"
# serde_with = "3"
rmp-serde = "1"

[dev-dependencies]
serde_json = "1"
ciborium = "0.2"

[features]
default = ["generate"]
generate = ["dep:rand_core"]
