[package]
name = "signify-test"
version = "0.1.0"
edition = "2021"

[dependencies]
libsignify = { version = "0.6", features = ["std"] }

rand_core = { version = "0.6.4", features = ["std"] }
jiff = { version = "0.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64ct = { version = "1", features = ["std"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
hex = "0.4.3"
thiserror = "2"
