[package]
name = "signify-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# libsignify = { version = "0.6.0", features = ["std"] }
libsignify = { path = "../signify-rs/libsignify/", features = ["std"] }

rand_core = { version = "0.6.4", features = ["std"] }
jiff = { version = "0.1", features = ["serde"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
